name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: "0.13.0"
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - run: zig build -Dinstall-headers --verbose --summary new
      - run: zig build test -Dplatform=linux_amd64_gcc4 --summary new
      - run: tree -ash zig-out
